### ISSUE TITLE
improvement to error messages

### ISSUE THREAD

**Issue by douglassdavis** [moxiecode/plupload#1103]
The standard error message when a file is too large, "File size error" is not very useful.

The plupload design should allow for error messages to use substitutions that show initialization parameters.  I shouldn't have to do this in the Javascript I write, it should be something configurable.

For example, it would be better if I could change the max file size error to:

The maximum file size is {max_file_size}.

Actually, that should be the standard error message in the core.

**Comment by Singh29** [comment]
Hi,I really need help for below 3 issues that i need to work on.
Help Appreciated..!!

So here are the 3 things ,

1. Can we set the Plupload error messages will close automatically after few seconds...like the jgrowl messages.
2. Can we close the plupload automatically once the file upload is complete.
3. I am using plupload and everything working fine only the issues is the thumbnail view doesn't
![img](https://cloud.githubusercontent.com/assets/14303339/10682704/a31a58b8-78fe-11e5-952c-c4bd3f3967e8.png)
 show the images.please see the screenshot attached.

**Comment by bryanroth** [comment]
The problem is that there is a default `error` event bound when the plupload UI widget is initialized that displays a set of default error messages when an error occurs during upload.

So, if you write a custom event handler for the `error` event your handler will always get called before the widget's default `error` event handler. Any error message you display using the `notify` method gets hidden by the default `error` handler when it calls `notify`.

It would be nice if you could just set a custom error message to display.

**Comment by jayarjo** [comment]
You could simply create custom language pack and map corresponding messages to whatever you find more appropriate.

I'm afraid currently we are not planning to make further changes to error messages.
