### ISSUE TITLE
Can't browse pictures on ios 8.0.2 using html5 or html4 runtimes

### ISSUE THREAD

**Issue by elfif** [moxiecode/plupload#1144]
Hi there.

I can't browse pictures on safari with ios 8.0.2 using html5 or html4 runtimes. When i click the add files button nothing happens. Itried the same thing using chrome on ios and it works perfect.
In fact it works everywhere except on my ipad ....
I also tested a "standard" input-file field with a standard upload using the same ipad and it works fine.

If someone has an idea....

**Comment by mschipperheyn** [comment]
Yeah, removing display:none fixed it for me. I would recommend plupload doing that itself before it loads. I'm not sure if the same problem applies if a surrounding element has display:none applied

**Comment by kaige11** [comment]
I met the problem too and i fixed it just by download the latest version of plupload , good luck!

**Comment by jayarjo** [comment]
If any of the containers are not visible by the moment Plupload initializes, we cannot place the browse button properly (since invisible elements do not have neither size, nor position). For this reason we have a special method on the uploader object - `refresh()`.

So simply call `uploader.refresh()` whenever you finally decide to display the target element.
