### ISSUE TITLE
user related upload directory

### ISSUE THREAD

**Issue by reproplan** [moxiecode/plupload#1168]
hi there,
1st of all, great extension.
Is there a possibility to create a user related uploadfolder while uploading files?
that any file a logged in user uploads is located in that user-folder?

Kind regards,
Matthias

**Comment by cmb69** [comment]
Yes, but this issue is not really related to Plupload, but to the program that processes the uploaded file. An example of such a program is [examples/upload.php](https://github.com/moxiecode/plupload/blob/master/examples/upload.php), where you could adjust $targetDir according to the logged in user.
