### ISSUE TITLE
filetype "jpEg" is missing

### ISSUE THREAD

**Issue by Daijobou** [moxiecode/plupload#1263]
In version 2.1.4 and 2.1.5 all files with type "JPEG" are not show up in dialogbox. Only "JPG".

**Comment by jayarjo** [comment]
Do you specify `.jpeg` extension in the list of extensions? Post your config.

**Comment by Daijobou** [comment]
In 2.1.3 "jpEg" working fine with this settings:
mime_types: [{title:'Image files',extensions:'jpg,gif,png'}]

In 2.1.4 and 2.1.5 only "jpg" will be found. "jpEg" is only a  "jpg" file.

**Comment by nebrot** [comment]
Example Plupload UI 2.1.7: http://jsfiddle.net/9dnxvy93/8/

```javascript
$("#uploader").plupload(
{
	runtimes: "html5",
	url: '/echo/json/',
	multi_selection: false,
	autostart: false,
	dragdrop: false,
	views: 
	{
		list: false,
		thumbs: true
	},
	filters: 
	[{
		title : "Dateien", extensions : "jpg,jpeg"
	}]
});
```


Win 8.1 Firefox 39: only jpg, no jpeg
![plupload_firefox](https://cloud.githubusercontent.com/assets/6941112/8796304/11227ebc-2f94-11e5-94fc-b29c47cdee11.png)



Win 8.1 Chrome 43: jpg and jpeg
![plupload_chrome](https://cloud.githubusercontent.com/assets/6941112/8796308/136a7fb2-2f94-11e5-81fe-d75445e2cc47.png)

**Comment by jayarjo** [comment]
Looks like they've changed the logic for `accept` attribute and [now support extensions in the list](https://developer.mozilla.org/en-US/Firefox/Releases/37#HTML), since version 37. Until now we only had it in the Chrome/Safari and IE10+. I will add Firefox in the list as well.

However, @jochemmeyers, [it was reported](https://bugzilla.mozilla.org/show_bug.cgi?id=826176#c62) that there is some kind of problem with `.tif` extension. While this is definitely an inconvenience, browsers still provide a way to select the files, via _All files_ option. I guess that's what we have to rely upon, until browser vendors settle down with their feature updates.

**Comment by Laubeee** [comment]
Any progress / workaround for this yet? (jpg / jpeg problem in FF)

**Comment by jayarjo** [comment]
Firefox seems to handle this properly now.
