### ISSUE TITLE
Some of IE 11 : Object doesn't support property or method "widget"

### ISSUE THREAD

**Issue by fjmiaoxiao** [moxiecode/plupload#1268]
This error occurred in some of IE 11 when trying to upload, while other browsers(including all other browsers in the same device and most of IE 11 in other devices) appeared to be normal .  Can't indentify the cause.

**Comment by jayarjo** [comment]
Which Plupload version are you using?

**Comment by fjmiaoxiao** [comment]
2.1.7

**Comment by jayarjo** [comment]
Well... since you do not provide any more details, I can only guess that jQuery UI is not loaded by the moment that Plupload UI requires it. Might be something about the order in which you load the scripts. Also make sure that you do not encounter any javascript errors in other (non-Plupload related) scripts that you load before Plupload.

**Comment by fjmiaoxiao** [comment]
THX, however I have loaded jQuery and jQuery UI. I gave up on these IE Freak because they are too rare, for now I tried over 30 devices and only 2 of them shared the problem, I'm gonna asumme that it is caused by the setting of IE. Maybe it is easier to find out the cause when I encounter more situation like this.

**Comment by fjmiaoxiao** [comment]
THX, however I have loaded jQuery and jQuery UI. I gave up on these IE Freak because they are too rare, for now I tried over 30 devices and only 2 of them shared the problem, I'm gonna asumme that it is caused by the setting of IE. Maybe it is easier to find out the cause when I encounter more situation like this.
