### ISSUE TITLE
`Error` callback is bound too late.

### ISSUE THREAD

**Issue by d-ph** [moxiecode/plupload#1375]
Hello,

The `Error` callback function is bound too late in `plupload.Uploader` constructor, causing some init errors to fail silently. This happens only, when the `Error` callback is passed via the options.init like this:

``` javascript
new plupload.Uploader({
  init: {
    Error: function () {}
  }
})
```

It works, if you bind this callback manually, before calling `.init()`, like this:

``` javascript
var uploader = plupload.Uploader({});
uploader.bind('Error', function () {});
uploader.init();
```

Steps to reproduce:
1. Take the code from this [tutorial](http://www.plupload.com/examples/core)
2. Remove the `browse_button` option to cause an init error.
3. Run the code.

Result:
No errors are logged anywhere and the `Error` callback is not called, but the uploading doesn't work.

Expected result:
The `Error` callback is called.

As I said, the `Error` callback is called, when bound manually with `uploader.bind()`.

**Comment by jayarjo** [comment]
I'm afraid this is expected behavior. It followed Plupload historically and probably won't change. So basically there are several ways to attach event listeners: in the config, before you call `uploader.init()` and after you call `uploader.init()`. The last one is the safest, however if you need to intervene and cancel default event handlers for example, or get the early error notifications like in your case, you need to either attach your listeners in the config or before invocation of uploader.init().
