### ISSUE TITLE
Error using HTML4 runtime when server set the X-Frame-Options

### ISSUE THREAD

**Issue by Hanastaroth** [moxiecode/plupload#1391]
When using IE9 and HTML4 runtime (I can't use the flash runtime) I ran into some problems. 

The server does correctly answer `HTTP 200 OK` but for plupload there is an error `404`. 

Here is the server response:

```
HTTP/1.1 200 OK
Server: nginx/1.11.1
Date: Mon, 18 Jul 2016 16:17:25 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 92
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, PUT, DELETE, OPTIONS
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: Authorization, Content-Type, Accept
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Application-Context: application

{"ref":"20160718_181544403_avatar_200.jpg","fileName":"avatar_200.jpg","size":13615}
```

Here is the trace of the error : 

```
{  
   "code":-200,
   "message":"HTTP Error.",
   "file":{  
      "id":"o_1anvcfbs91qf6j33jid8bm16o7a",
      "name":"avatar_200.jpg",
      "type":"image/jpeg",
      "loaded":0,
      "percent":0,
      "status":2,
      "lastModifiedDate":"18/7/2016 18:12:27"
   },
   "response":null,
   "status":404,
   "responseHeaders":""
}
```

I tried two different values for the `X-Frame-Options` (`DENY` and `SAMEORIGIN`). The `DENY` value cause the error when the `SAMEORIGIN` does not.

I could not find any clue on why does this happen.

**Comment by frickelbruder** [comment]
As the HTML4 Version uses an iframe to fake an ajax upload request, this is the perfectly valid and expected behaviour. The upload request will be send to the server and the response, which will be displayed in the "upload iframe" is blocked, due to the "X-Frame-Options: DENY" header.
Read more at: https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options

So this is not really related to plupload, but to your websites configuration. If you rely on the html4 upload, you should definitely use "X-Frame-Options: SAMEORIGIN" (or a matching variant of "X-Frame-Options: ALLOW-FROM https://example.com/")
