### ISSUE TITLE
Uncaught ReferenceError: mOxie is not defined

### ISSUE THREAD

**Issue by zsynacl** [moxiecode/plupload#1434]
I'm new to plupload and I tried a small example and got this error: 
`Uncaught ReferenceError: mOxie is not defined`

I was using the latest Chromium and Firefox, they both reported the same error, my include file looked like this:

```javascript
    <meta charset="utf-8">
    <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="css/index.css"/>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/plupload/js/moxie.min.js"></script>
    <script src="js/plupload/js/plupload.min.js"></script>
    <script src="js/plupload/js/i18n/zh_CN.js"></script>
    <script src="js/index.js" type="text/javascript"></script>
    <script src="js/common.js" type="text/javascript"></script>
```

the error occurred here:
```javascript
<script type="text/javascript">
        mOxie.Env.swf_url = './flash/Moxie.min.swf'; // Uncaught ReferenceError: mOxie is not defined
</script>
```

I searched for this issue [here](https://github.com/moxiecode/plupload/issues/1332)  but I couldn't get it.

**Comment by jayarjo** [comment]
We've removed `mOxie` namespace (as well as `o.` namespace), 'cause there were complaints about glogbal namespace pollution on our side. And we agreed. It is still possible to compile in that missing compatibility shim or to include it manually (it's just small wrapper script that can be found [here](https://github.com/moxiecode/plupload/blob/2.2.x/tests/js/o.js) for example).

But in your case you can instead simply do: `plupload.ua.swf_url = './flash/Moxie.min.swf';`. Since both `mOxie.Env` and `plupload.ua` are basically aliases to: `moxie.core.utils.Env`.

**Comment by zsynacl** [comment]
that's a solution, thanks a lot.
