### ISSUE TITLE
Preview image is aways fire onerror

### ISSUE THREAD

**Issue by kanbekotori** [moxiecode/plupload#1469]
Version: 2.3.2

I am using webpack.

```
const plUpload      = require('plupload');
const moxie         = require('libs/moxie');//moxie.js is copy from plupload/js/moxie.js

uploader.bind('FilesAdded', function(up, files) {
      files.forEach(function(file) {
        var item = new UploadFile(file);
        var preloader = new moxie.image.Image();
        preloader.onload = function() {
          preloader.downsize( 45, 45 );
          var dataUrl = preloader.getAsDataURL();
          item.setImage(dataUrl);
        };
        preloader.onerror = function() {
          console.log(arguments);
        };
        preloader.load( file.getSource() );
      });
    });
```

Select jpeg, png image file is aways get error.
![ecae43de-9edc-459a-aef6-70f0df1e036d](https://cloud.githubusercontent.com/assets/6301140/24831238/fcf1ce56-1cc8-11e7-8255-3f7c2cbed75f.png)

**Comment by nguyenj** [comment]
I'm getting this exact error.

Seems to be coming from here: https://github.com/moxiecode/moxie/blob/7056172e445829a84a6f7a41447f721523fd7773/src/javascript/runtime/RuntimeClient.js#L116

`options` is `null`.

**Comment by jayarjo** [comment]
@nguyenj are you also requiring moxie separately? Plupload already includes one, so FIle objects in Plupload are constructed with one constructor and then you are feeding it to another instance of moxie which compares it against it's own constructor and fails in that. At least that's what is happening for me. I guess I need to replace `instanceof` check with something else and also expose Plupload's own moxie, so that one wouldn't require to include another one manually.

**Comment by jayarjo** [comment]
So once `moxie` is exposed under plupload namespace, instead of: `const moxie  = require('libs/moxie');`, one would do `const moxie = plupload.moxie;`

**Comment by nguyenj** [comment]
@jayarjo Awesome! I look forward to the release, thanks for looking into this.

**Comment by nguyenj** [comment]
Thanks!
