### ISSUE TITLE
runtime 'flash'  error (-500 Init error)

### ISSUE THREAD

**Issue by Theoton** [moxiecode/plupload#1494]
it will throw error -500 (test in IE8/IE9/Chrome 56+):

```javascript
import plupload from 'plupload' //node_module @2.3.1 use with React

const uploader = new plupload.Uploader({
    container:  'container',
    browse_button: 'browsebtn',
    runtimes: 'flash',
    multipart: true,
    chunk_size: '0',
    url: uploadUrl,
    flash_swf_url: '/plupload-2.3.1/js/Moxie.swf',
});
```

node `<div><object value='swfurl'/></div>` has been appended to container,
but it dosn't work.

There is no error using the following method:

```html
<script src="/plupload-2.3.1/js/plupload.full.min.js"></script>

const uploader = new window.plupload.Uploader({
    container:  'container',
    browse_button: 'browsebtn',
    runtimes: 'flash',
    multipart: true,
    chunk_size: '0',
    url: uploadUrl,
    flash_swf_url: '/plupload-2.3.1/js/Moxie.swf', 
});
```

**Comment by jayarjo** [comment]
This is an interesting issue, that I thought would never arise... like - why would anyone want to use flash runtime in React environment?.. Why do you by the way?

The problem is caused by two facts: 
1. flash requires some global callback to notify an uploader that it has been successfully initialised.
2. when plupload is imported like that, it has no global namespace, hence flash has nobody to notify.

If you absolutely require flash to function in such environment consider replacing an expected global callback with your own:

```javascript
import plupload from 'plupload' //node_module @2.3.1 use with React

window.flash_callback_with_unique_name = function (event) {
    plupload.Uploader.prototype.dispatchEvent(event);
};

plupload.ua.global_event_dispatcher = 'flash_callback_with_unique_name';

const uploader = new plupload.Uploader({
    container:  'container',
    browse_button: 'browsebtn',
    runtimes: 'flash',
    multipart: true,
    chunk_size: '0',
    url: uploadUrl,
    flash_swf_url: '/plupload-2.3.1/js/Moxie.swf'
});

uploader.init();
```

**Comment by webKity** [comment]
I have the same problem because i want my app run in IE9

**Comment by Theoton** [comment]
@jayarjo Thanks! It's  OK
