### ISSUE TITLE
examples/upload.php allows unauthenticated file uploads

### ISSUE THREAD

**Issue by lcashdol** [moxiecode/plupload#1536]
Hi,

If php.ini has upload_tmp_dir defined files can be uploaded to the web server without authentication.    If it's in the path of the web server you can upload .php and execute code. This impacts v3 and v2 of the software.

**Comment by jayarjo** [comment]
It was never meant to be used in production out of the box. Also it is not recommended in general to allow php (or any other executable files) files to be uploaded into your document root.

**Comment by asmecher** [comment]
This example script is responsible for several vulnerabilities in the wild in applications that include plupload:
- https://vulners.com/zdt/1337DAY-ID-23323
- https://www.whitesourcesoftware.com/vulnerability-database/CVE-2018-16388
- https://www.drupal.org/project/plupload/issues/1895328
- https://support.alertlogic.com/hc/en-us/articles/115005896463-CMS-Plupload-Arbitrary-File-Upload-
- https://www.mageni.net/vulnerability/wordpress-omni-secure-files-plugin-uploadphp-arbitrary-file-upload-vulnerability-802641

While it is true that there is a disclaimer at the top of the file, it obviously hasn't been read/noticed by plupload users. Those using plupload as e.g. a composer dependency aren't warned to secure this file.

I would recommend some combination of the following:
- Fix the upload.php script so it's safe from e.g. arbitrary directory traversals. This would encourage better practices from those following the example, and make the example script safer if it's deployed in a web-executable location.
- Defuse the script:
  - Rename the upload.php script to e.g. `upload.php.txt` so that it cannot be accidentally deployed and executed, or
  - Add an `exit()` call to to the top of the script, near the disclaimer about insecurity.

**Comment by jayarjo** [comment]
@asmecher I like your suggestions. I guess the problem comes from the fact that this package was created without possibility  of being served by package managers in mind. It was adapted for them later on. Unfortunately I don't have control over this package anymore. Also I don't think it is actively used by people anyway. At least I don't see a reason to use it these days.

**Comment by spocke** [comment]
Updated the composer packages for v3 (3.1.3) and v2 (2.3.7) to disable execution of those scripts by adding a `die` call to the top of the files. I will see if I can send a report to packagist to flag the earlier versions as insecure.

**Comment by asmecher** [comment]
Thanks for the quick turn-around on the Composer update, @jayarjo and @spocke! This addresses the initial problem, but for bonus points I think it would be a good idea to fix the directory traversal flaw -- `$_FILES["file"]["name"]` is trusted as part of the destination filepath and can be easily abused to upload the file to an arbitrary location on the server. Even just wrapping it in `basename` would be an improvement. But if that's out of scope given the disclaimer and changes you've already made, I'm OK with that.

**Comment by lcashdol** [comment]
I'll close this out as the original issue has been resolved.

**Comment by asmecher** [comment]
@lcashdol, would you like the arbitrary directory traversal issue to be filed elsewhere?

**Comment by lcashdol** [comment]
Actually, that would be good. It will give you credit for discovering the issue as well.
