### ISSUE TITLE
Feature request - prevent multiple and limit number of files

### ISSUE THREAD

**Issue by JonoB** [moxiecode/plupload#625]
There are two big items missing from plupload:
1. Ability to limit number of files selected. I've seen lots of hacks on the forums, but this needs to be in the core.
2. Prevent adding the same file more than once in the same upload

Both of these are covered in http://www.plupload.com/punbb/viewtopic.php?id=695 and should be in core.

**Comment by jayarjo** [comment]
Currently we have a filter that [prevents duplicates](https://github.com/moxiecode/plupload/wiki/Options#filters.prevent_duplicates). A way to constrain number of files in the queue [is available in UI widget](https://github.com/moxiecode/plupload/wiki/UI.Plupload), however it can be easily ported to the Core API, since the API for creating custom file filters [is exposed](https://github.com/moxiecode/plupload/wiki/File-Filters).
